name: Request Members
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v4
      # Install Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install @octokit/action
      # Node.js script can be anywhere. A good convention is to put local GitHub Actions
      # into the `.github/actions` folder
      - run: node .github/actions/get-members.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
